routes:
    "https://{all}/": { type: upstream, upstream: "app:http" }
    "http://{all}/": { type: redirect, to: "https://{all}/" }

services: 
    database:
        type: postgresql:15

    

applications:
    app:
        source:
            root: "/"

        stack:
            - "php@8.3":
              extensions:
                  - apcu
                  - pdo_pgsql
                  - xsl

            - "nodejs@18"
            - frankenphp
            - bzip2


        variables:
            php:
                opcache.preload: config/preload.php

        web:
            locations:
                "/":
                    root: "public"
                    #expires: 1h
                    #index:
                    #    - index.php
                    passthru: true
                    scripts: false
                    allow: false

            upstream:
                socket_family: tcp # important for PHP we default to unix sockets
                protocol: http
            commands:
                start: ./frankenphp php-server --listen=localhost:$PORT --root=$PLATFORM_DOCUMENT_ROOT

        mounts:
            "/var": { source: storage, source_path: var }
            #".local": {source: storage, source_path: caddy-local}

        relationships:
            database:
                service: database
                endpoint: postgresql
            
        hooks:
            build: |
                set -x -e

                curl -fs https://get.symfony.com/cloud/configurator | bash

                NODE_VERSION=18 symfony-build

            deploy: |
                set -x -e

                symfony-deploy

        #crons:
        #    security-check:
        #        # Check that no security issues have been found for PHP packages deployed in production
        #        # See https://github.com/fabpot/local-php-security-checker
        #        spec: '50 23 * * *'
        #        cmd: if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then croncape php-security-checker; fi

        
